name: Symfony Docker Test

on: [push]

jobs:
  symfony:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker
        run: docker compose build --no-cache

      - name: Start Docker
        run: docker compose up -d

      - name: Install Dependencies
        run: docker compose exec -T php composer install --no-interaction --prefer-dist

      - name: Run Symfony checks
        run: docker compose exec -T php php bin/console about

      - name: DB Creation
        run: docker compose exec -T php php bin/console do:d:c

      - name: Migration
        run: docker compose exec -T php php bin/console do:mi:mi
      
      - name: Loading of Fixtures
        run: docker compose exec -T php php bin/console doctrine:fixtures:load

      - name: Test Case Execution
        run: docker compose exec -T php php bin/phpunit
      